// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bJSLnzQiU882Sm76eQ6ECs
// Component: uLTPE-ZqPg
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: bJSLnzQiU882Sm76eQ6ECs/projectcss
import * as sty from "./PlasmicAntdFormLabel.module.css"; // plasmic-import: uLTPE-ZqPg/css

export type PlasmicAntdFormLabel__VariantMembers = {};

export type PlasmicAntdFormLabel__VariantsArgs = {};
type VariantPropType = keyof PlasmicAntdFormLabel__VariantsArgs;
export const PlasmicAntdFormLabel__VariantProps = new Array<VariantPropType>();

export type PlasmicAntdFormLabel__ArgsType = {};
type ArgPropType = keyof PlasmicAntdFormLabel__ArgsType;
export const PlasmicAntdFormLabel__ArgProps = new Array<ArgPropType>();

export type PlasmicAntdFormLabel__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultAntdFormLabelProps {
  className?: string;
}

function PlasmicAntdFormLabel__RenderFunc(props: {
  variants: PlasmicAntdFormLabel__VariantsArgs;
  args: PlasmicAntdFormLabel__ArgsType;
  overrides: PlasmicAntdFormLabel__OverridesType;
  dataFetches?: PlasmicAntdFormLabel__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAntdFormLabel__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAntdFormLabel__VariantsArgs;
    args?: PlasmicAntdFormLabel__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicAntdFormLabel__Fetches;
  } & Omit<PlasmicAntdFormLabel__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicAntdFormLabel__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicAntdFormLabel__ArgProps,
      internalVariantPropNames: PlasmicAntdFormLabel__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicAntdFormLabel__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAntdFormLabel";
  } else {
    func.displayName = `PlasmicAntdFormLabel.${nodeName}`;
  }
  return func;
}

export const PlasmicAntdFormLabel = Object.assign(
  // Top-level PlasmicAntdFormLabel renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicAntdFormLabel
    internalVariantProps: PlasmicAntdFormLabel__VariantProps,
    internalArgProps: PlasmicAntdFormLabel__ArgProps
  }
);

export default PlasmicAntdFormLabel;
/* prettier-ignore-end */
