// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bJSLnzQiU882Sm76eQ6ECs
// Component: 1atgvBhq39
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import AntdForm from "../../AntdForm"; // plasmic-import: DOh18PmYvp/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: bJSLnzQiU882Sm76eQ6ECs/projectcss
import * as sty from "./PlasmicAndFormDosage.module.css"; // plasmic-import: 1atgvBhq39/css

export type PlasmicAndFormDosage__VariantMembers = {};

export type PlasmicAndFormDosage__VariantsArgs = {};
type VariantPropType = keyof PlasmicAndFormDosage__VariantsArgs;
export const PlasmicAndFormDosage__VariantProps = new Array<VariantPropType>();

export type PlasmicAndFormDosage__ArgsType = {};
type ArgPropType = keyof PlasmicAndFormDosage__ArgsType;
export const PlasmicAndFormDosage__ArgProps = new Array<ArgPropType>();

export type PlasmicAndFormDosage__OverridesType = {
  root?: p.Flex<typeof AntdForm>;
};

export interface DefaultAndFormDosageProps {
  className?: string;
}

function PlasmicAndFormDosage__RenderFunc(props: {
  variants: PlasmicAndFormDosage__VariantsArgs;
  args: PlasmicAndFormDosage__ArgsType;
  overrides: PlasmicAndFormDosage__OverridesType;
  dataFetches?: PlasmicAndFormDosage__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <AntdForm
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames("__wab_instance", sty.root)}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: typeof AntdForm;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAndFormDosage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAndFormDosage__VariantsArgs;
    args?: PlasmicAndFormDosage__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicAndFormDosage__Fetches;
  } & Omit<PlasmicAndFormDosage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicAndFormDosage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicAndFormDosage__ArgProps,
      internalVariantPropNames: PlasmicAndFormDosage__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicAndFormDosage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAndFormDosage";
  } else {
    func.displayName = `PlasmicAndFormDosage.${nodeName}`;
  }
  return func;
}

export const PlasmicAndFormDosage = Object.assign(
  // Top-level PlasmicAndFormDosage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicAndFormDosage
    internalVariantProps: PlasmicAndFormDosage__VariantProps,
    internalArgProps: PlasmicAndFormDosage__ArgProps
  }
);

export default PlasmicAndFormDosage;
/* prettier-ignore-end */
