// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bJSLnzQiU882Sm76eQ6ECs
// Component: g2haT3nDznE1
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import AntdDatePicker from "../../AntdDatePicker"; // plasmic-import: VEazoruVyc/component
import AntdFormInput from "../../AntdFormInput"; // plasmic-import: RJj2IYTf9q/component
import AntdFileUpload from "../../AntdFileUpload"; // plasmic-import: o5fKIqH7Zk/component
import AntdFormSubmit from "../../AntdFormSubmit"; // plasmic-import: P0m14OaWFw/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: bJSLnzQiU882Sm76eQ6ECs/projectcss
import * as sty from "./PlasmicHomepage.module.css"; // plasmic-import: g2haT3nDznE1/css

export type PlasmicHomepage__VariantMembers = {};

export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: p.Flex<"div">;
  antdDatePicker?: p.Flex<typeof AntdDatePicker>;
  h1?: p.Flex<"h1">;
  antdFileUpload?: p.Flex<typeof AntdFileUpload>;
  antdFormSubmit?: p.Flex<typeof AntdFormSubmit>;
};

export interface DefaultHomepageProps {
  className?: string;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  dataFetches?: PlasmicHomepage__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <React.Fragment>
      {}
      {}

      <div className={defaultcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(defaultcss.all, sty.freeBox__jET2)}
          >
            <div className={classNames(defaultcss.all, sty.freeBox__nTHe)}>
              <AntdDatePicker
                data-plasmic-name={"antdDatePicker"}
                data-plasmic-override={overrides.antdDatePicker}
                className={classNames("__wab_instance", sty.antdDatePicker)}
              />
            </div>

            <h1
              data-plasmic-name={"h1"}
              data-plasmic-override={overrides.h1}
              className={classNames(
                defaultcss.h1,
                defaultcss.__wab_text,
                sty.h1
              )}
            >
              {"Prescription Form"}
            </h1>

            <AntdFormInput
              className={classNames("__wab_instance", sty.antdFormInput__xd91G)}
              label={"Name" as const}
              type={"text" as const}
            />

            <AntdFormInput
              className={classNames("__wab_instance", sty.antdFormInput__rmtX2)}
              label={"Age" as const}
              type={"number" as const}
            />

            <AntdFormInput
              className={classNames("__wab_instance", sty.antdFormInput__rgmsz)}
              label={"Prescription ID" as const}
              type={"text" as const}
            />

            <AntdFormInput
              className={classNames("__wab_instance", sty.antdFormInput__aSukO)}
              label={"Medicine" as const}
              placeholder={"medicine1" as const}
              type={"text" as const}
            />

            <AntdFileUpload
              data-plasmic-name={"antdFileUpload"}
              data-plasmic-override={overrides.antdFileUpload}
              className={classNames("__wab_instance", sty.antdFileUpload)}
            />

            <AntdFormSubmit
              data-plasmic-name={"antdFormSubmit"}
              data-plasmic-override={overrides.antdFormSubmit}
              className={classNames("__wab_instance", sty.antdFormSubmit)}
            />
          </p.Stack>
        </p.Stack>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "antdDatePicker", "h1", "antdFileUpload", "antdFormSubmit"],
  antdDatePicker: ["antdDatePicker"],
  h1: ["h1"],
  antdFileUpload: ["antdFileUpload"],
  antdFormSubmit: ["antdFormSubmit"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  antdDatePicker: typeof AntdDatePicker;
  h1: "h1";
  antdFileUpload: typeof AntdFileUpload;
  antdFormSubmit: typeof AntdFormSubmit;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicHomepage__Fetches;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    antdDatePicker: makeNodeComponent("antdDatePicker"),
    h1: makeNodeComponent("h1"),
    antdFileUpload: makeNodeComponent("antdFileUpload"),
    antdFormSubmit: makeNodeComponent("antdFormSubmit"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
