// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bJSLnzQiU882Sm76eQ6ECs
// Component: 0gPS1xrMsR
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: bJSLnzQiU882Sm76eQ6ECs/projectcss
import * as sty from "./PlasmicAntdFormNumber.module.css"; // plasmic-import: 0gPS1xrMsR/css

export type PlasmicAntdFormNumber__VariantMembers = {};

export type PlasmicAntdFormNumber__VariantsArgs = {};
type VariantPropType = keyof PlasmicAntdFormNumber__VariantsArgs;
export const PlasmicAntdFormNumber__VariantProps = new Array<VariantPropType>();

export type PlasmicAntdFormNumber__ArgsType = {};
type ArgPropType = keyof PlasmicAntdFormNumber__ArgsType;
export const PlasmicAntdFormNumber__ArgProps = new Array<ArgPropType>();

export type PlasmicAntdFormNumber__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultAntdFormNumberProps {
  className?: string;
}

function PlasmicAntdFormNumber__RenderFunc(props: {
  variants: PlasmicAntdFormNumber__VariantsArgs;
  args: PlasmicAntdFormNumber__ArgsType;
  overrides: PlasmicAntdFormNumber__OverridesType;
  dataFetches?: PlasmicAntdFormNumber__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAntdFormNumber__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAntdFormNumber__VariantsArgs;
    args?: PlasmicAntdFormNumber__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicAntdFormNumber__Fetches;
  } & Omit<PlasmicAntdFormNumber__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicAntdFormNumber__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicAntdFormNumber__ArgProps,
      internalVariantPropNames: PlasmicAntdFormNumber__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicAntdFormNumber__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAntdFormNumber";
  } else {
    func.displayName = `PlasmicAntdFormNumber.${nodeName}`;
  }
  return func;
}

export const PlasmicAntdFormNumber = Object.assign(
  // Top-level PlasmicAntdFormNumber renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicAntdFormNumber
    internalVariantProps: PlasmicAntdFormNumber__VariantProps,
    internalArgProps: PlasmicAntdFormNumber__ArgProps
  }
);

export default PlasmicAntdFormNumber;
/* prettier-ignore-end */
