// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicAntdMedicineInput,
  DefaultAntdMedicineInputProps
} from "./plasmic/presc_codegen/PlasmicAntdMedicineInput";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import { Form, Input, InputNumber, Select } from "antd";

interface AntdMedicineInputProps extends DefaultAntdMedicineInputProps { }

function AntdMedicineInput_(
  props: AntdMedicineInputProps,
  ref: HTMLElementRefOf<"div">
) {
  const [medicineData, setMedicineData] = React.useState([]);
  const [error, setError] = React.useState(null);

  const fetchMedicineData = React.useCallback(async () => {
    try {
      const response = await fetch('https://prescription-app-84502-default-rtdb.firebaseio.com/medicines.json');
      console.log(response);
      if (!response.ok) {
        throw Error('Something went wrong !');
      }
      const data = await response.json();
      const loadedData: any = [];
      for (const key in data) {
        loadedData.push({
          id: key,
          label: data[key].name,
          value: data[key].name
        })
      }
      console.log(loadedData);
      setMedicineData(loadedData);
    } catch (error) {
      setError(error.message);
    }
  }, []);

  React.useEffect(() => {
    fetchMedicineData().catch((error) => {
      setError(error.message);
    });
  }, []);


  return (
    <Form.Item className={props.className}
      label={props.label}
      name="medicineInput"
    >
      <Input.Group compact>
        <Select defaultValue="Medication" style={{ width: '60%' }} options={medicineData}>
        </Select>
        <InputNumber style={{ width: '40%' }} placeholder="Dosage" />
      </Input.Group>
    </Form.Item>
  )
}

const AntdMedicineInput = React.forwardRef(AntdMedicineInput_);
export default AntdMedicineInput;
